#!/usr/bin/env bash

# Command substitution: get current date and current user
TODAY=$(date +'%A, %B %d, %Y')
CURRENT_USER=$(whoami)

# Environment variable, defaulting to "Unknown" if not set
PROJECT_NAME=${PROJECT:-"Unknown Project"}

# Heredoc: generate a text file report
cat <<- EOF > ~/system_report.txt
	====================================
	System Report
	====================================
	Date: $TODAY
	Generated by: $CURRENT_USER
	Project: $PROJECT_NAME
	Current Directory: $PWD
	====================================
EOF

echo "Report generated at ~/system_report.txt"
